DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `STAMPS_FOR_HOME`(IN userId INT, IN idTema INT)
BEGIN
	SELECT S.STAMP_ID stampId, S.NAME,S.DESCRIPTION, 
	S.PATH, IFNULL(ASD.PROM_VALOR, 0) totalRating, S.PRICE, 
	S.THEME_ID themeId, T.NAME themeName, U.USER_ID artistId, 
	CONCAT(U.FIRST_NAME, ' ' , U.LAST_NAME) artistName 
	FROM STAMP S 
	INNER JOIN USER U ON S.USER_ID = U.USER_ID 
	INNER JOIN THEME T ON S.THEME_ID = T.THEME_ID
	LEFT JOIN (
	SELECT ROUND(AVG(R.VALUE)) PROM_VALOR, S.STAMP_ID FROM RATING R
	INNER JOIN R_RATING_STAMP RRS ON R.RATING_ID = RRS.RATING_ID 
	INNER JOIN STAMP S ON RRS.STAMP_ID = S.STAMP_ID
	GROUP BY RRS.STAMP_ID
	) AS ASD ON ASD.STAMP_ID = S.STAMP_ID
    where (S.USER_ID = userId or userId = 0) and (S.THEME_ID = idTema or idTema = 0);
END ;; 
DELIMITER ;